<?php

return [

    'shipping-50' => [
        'id' => 'shipping-50',
        'type' => 'voucher',
        'benefit_type' => 'shipping',
        'reward_type' => 'shipping',
        'value' => 50,
        'minimum' => 100,
        'label' => '₱50 OFF Shipping',
        'reward_label' => '₱50 OFF',
        'condition' => 'Minimum spend ₱100',
        'reward_condition' => 'On orders over ₱100.00',
        'source' => 'SARI Marketplace',
        'tag' => 'EXTRA',
    ],

    'shipping-25' => [
        'id' => 'shipping-25',
        'type' => 'voucher',
        'benefit_type' => 'shipping',
        'reward_type' => 'shipping',
        'value' => 25,
        'minimum' => 50,
        'label' => '₱25 OFF Shipping',
        'reward_label' => '₱25 OFF',
        'condition' => 'Minimum spend ₱50',
        'reward_condition' => 'On orders over ₱50.00',
        'source' => 'SARI Marketplace',
        'tag' => 'POPULAR',
    ],

    'discount-8' => [
        'id' => 'discount-8',
        'type' => 'discount',
        'benefit_type' => 'subtotal',
        'reward_type' => 'shop',
        'value' => 8,
        'minimum' => 100,
        'label' => '8% OFF',
        'reward_label' => '8% OFF',
        'condition' => 'Minimum spend ₱100',
        'reward_condition' => 'On orders over ₱100.00',
        'source' => 'SARI Marketplace',
        'tag' => 'LIMITED',
    ],

    'discount-10' => [
        'id' => 'discount-10',
        'type' => 'discount',
        'benefit_type' => 'subtotal',
        'reward_type' => 'shop',
        'value' => 10,
        'minimum' => 150,
        'label' => '10% OFF',
        'reward_label' => '10% OFF',
        'condition' => 'Minimum spend ₱150',
        'reward_condition' => 'On orders over ₱150.00',
        'source' => 'SARI Marketplace',
        'tag' => 'LIMITED',
    ],

    'discount-15' => [
        'id' => 'discount-15',
        'type' => 'discount',
        'benefit_type' => 'subtotal',
        'reward_type' => 'shop',
        'value' => 15,
        'minimum' => 250,
        'label' => '15% OFF',
        'reward_label' => '15% OFF',
        'condition' => 'Minimum spend ₱250',
        'reward_condition' => 'On orders over ₱250.00',
        'source' => 'SARI Marketplace',
        'tag' => 'EXCLUSIVE',
    ],

    'discount-20' => [
        'id' => 'discount-20',
        'type' => 'discount',
        'benefit_type' => 'subtotal',
        'reward_type' => 'shop',
        'value' => 20,
        'minimum' => 500,
        'label' => '20% OFF',
        'reward_label' => '20% OFF',
        'condition' => 'Minimum spend ₱500',
        'reward_condition' => 'On orders over ₱500.00',
        'source' => 'SARI Marketplace',
        'tag' => 'BEST VALUE',
    ],

];